M48
; DRILL file {KiCad 9.0.6} date 2025-11-25T16:23:32+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-25T16:23:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X126.265Y-104.71
X126.265Y-110.49
T2
X125.9Y-119.0
X137.9Y-131.0
X172.15Y-119.0
X184.15Y-131.0
M30
